### ISSUE TITLE
README improvements

### ISSUE THREAD

**Issue by vitalyte** [TNTU-121-Software-Engineering/FIS-SE-SPs-42-Yaroslav-Lapovets-bachelor-thesis#1]
1. заберіть зайвий текст  `Move to directory and create docker-compose.yaml file` і все що доцього відноситься. Файл вже створений як я бачу.
2. Додайте версії в розділі 'Used technologies'
3. Цей перелік з ключовими технологіями і версіями варто додати окремим слайдом в презентацію останнім слайдом після дякую за увагу.
4. Будьте готові до питання чому саме така версія `Java 20`

**Comment by ZeroNeiron** [comment]
Переробив README та презентацію
